# Restart webpack-dev-server if you make changes here
default: &default
  enabled: true
  host: localhost
  port: 3000/packs

development:
  <<: *default

test:
  <<: *default
  enabled: false

production:
  <<: *default
  enabled: false
